export type AccountCreateArgs = {
	id?: number;
	username: string;
	code?: string;
	code2?: string;
	externalId?: string;
	email: string;
	password: string;
	confirmPassword: string;
	userId?: string | null;
	title?: string | null;
	firstName?: string | null;
	middleName?: string | null;
	lastName?: string | null;
	isActive?: boolean | null;
	isStaff?: boolean | null;
	image?: string | null;
	PhoneNumber?: string | null;
	gender?: number | null;
	dateBirth?: string | null | Date;
};
